name: ocicrypt-rs build
on: [push, pull_request, create]

jobs:
  ci:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly

    # Run all steps in the compilation testing containers
    container:
      image: runetest/compilation-testing:ubuntu18.04
      env:
        LD_LIBRARY_PATH: /usr/local/lib/rats-tls

    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Update cargo home
        run: |
          apt-get update && apt-get install -y cargo
          cp -r /root/.cargo /github/home/.cargo
      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Install tonic's protoc dependencies
        run: |
          apt install apt protobuf-compiler libprotobuf-dev
      - name: Build and install rats-tls
        run: | 
          apt-get install -y libcurl4-openssl-dev
          git clone https://github.com/inclavare-containers/rats-tls
          cd rats-tls
          cmake -DBUILD_SAMPLES=on -H. -Bbuild
          make -C build install

      - name: Install musl target to Rust toolchain
        run: |
          rustup target add x86_64-unknown-linux-musl

      - name: Run cargo musl build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --target=x86_64-unknown-linux-musl
